version: '3.8'

services:
  viral_api:
    image: icastrom/viral_api
    build:
      context: .
    env_file:
      - /home/viral_dev/constants/.env
    ports:
      - '8080:8080'
  soap_service:
    image: icastrom/soap_service_viral
    build:
      context: .
    env_file:
       - /home/viral_dev/constants/.env
    ports:
       - '8081:8080'
       - '3000:3000'